baseURL = "https://canisli.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Canis Li"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Canis Li"
  headline = "I'm a junior at Valley Christian High School interested in physics and astronomy. I'm currently investigating the optical brightness variations of ultraluminous X-ray source Holmberg II X-1. I play volleyball and love listening to classical music and c-pop. Check out my astrophotography below!"
  image = "canis.jpg"  # path relative to static directory

  links = [
    { link = {href="/Resume_CanisLi.pdf", text="Resume"} },
    { github = "https://github.com/canisli" },
    { linked = {href="https://www.linkedin.com/in/canisli", text="LinkedIn" } },
    { astro = {href= "astro/", text="Astrophotography"}},    
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
