baseURL = "https://canisli.github.io/"
languageCode = "en"
defaultContentLanguage = "en"

title = "Canis Li"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[author]
  name = "Canis Li"
  headline = """Hello! I'm a senior at Valley Christian High School interested in physics and astronomy. \
                 I'm currently researching photometric variations of stellar magnetic activity. \
                 I'm also an avid supporter for the dark sky movement. \
                 For fun, I play varsity volleyball and listen to j-pop and classical music. """
  image = "canis.jpg"  # path relative to static directory

  links = [
   # { link = {href="/Resume_CanisLi.pdf", text="Resume"} },
    { github = "https://github.com/canisli" },
    { linked = {href="https://www.linkedin.com/in/canisli", text="LinkedIn" } },
    { astro = {href= "astro/", text="Astrophotography"}},    
    { darksky = {href= "darksky/", text="Dark Sky"}}
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
