baseURL = "https://canis.li"
googleAnalytics = "G-T3Y23EN70G"
languageCode = "en"
defaultContentLanguage = "en"

title = "Canis Li"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
   name = "Canis Li"
   headline = "I’m an MIT undergraduate studying physics and computer science, with a focus on statistics and artificial intelligence. Outside of academics, I advocate for dark-sky preservation, practice piano, and play volleyball."
   image = "me2.jpg"  # path relative to static directory

  links = [
   # { link = {href="/Resume_CanisLi.pdf", text="Resume"} },
    { googlescholar ={href= "https://scholar.google.com/citations?user=Pld3_bQAAAAJ", text="Publications"}}, 
    { github = {href="https://github.com/canisli", text="GitHub"}},
    { linked = {href="https://www.linkedin.com/in/canisli", text="LinkedIn" }} ,
    { astro = {href= "astro/", text="Astrophotography"}},    
    # { darksky = {href= "darksky/", text="Dark-Sky"}},
    { articles = {href= "articles/", text="Reading List"}}
  ]
[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
